export const houseInfo = [
   {
      id: 1,
      title: "Современный дом",
      address: "улица Солнечная, 42, город Благополучие",
      price: "$3,000/mo",
      prevPrice: "$3,200/mo",
      beds: 4,
      baths: 3,
      garages: 2,
      area: 250,
      image: {
         url: "https://petrostroybaza.ru/wp-content/uploads/2020/05/ddivsr7r4i8.jpg",
         alt: "Современный 4-спальный дом с большим гаражом",
      },
      countPhoto: 14,
      countVideo: 3,
   },
   {
      id: 2,
      title: "Уютный коттедж",
      address: "проспект Зеленый, 15, поселок Новая Жизнь",
      price: "$1,800/mo",
      prevPrice: "$2,000/mo",
      beds: 3,
      baths: 2,
      garages: 1,
      area: 150,
      image: {
         url: "https://metalloy.ru/wp-content/uploads/2022/12/full_wey4ew1s.jpg",
         alt: "Уютный 3-спальный коттедж с красивым садом",
      },
      countPhoto: 8,
      countVideo: 1,
   },
   {
      id: 3,
      title: "Дом в классическом стиле",
      address: "бульвар Счастье, 28, город Мечты",
      price: "$4,500/mo",
      prevPrice: "$4,800/mo",
      beds: 5,
      baths: 4,
      garages: 3,
      area: 350,
      image: {
         url: "https://sjthemes.com/wp-content/uploads/2020/10/2-9-1024x576.jpg",
         alt: "Классический 5-спальный дом с большой террасой",
      },
      countPhoto: 24,
      countVideo: 5,
   },
   {
      id: 4,
      title: "Таунхаус в стиле минимализм",
      address: "улица Гармонии, 33, квартал Зеленый Город",
      price: "$2,200/mo",
      prevPrice: "$2,400/mo",
      beds: 3,
      baths: 2,
      garages: 1,
      area: 180,
      image: {
         url: "https://avatars.mds.yandex.net/i?id=f0c7c6f0968464d98508e132f3e0b945_l-3663589-images-thumbs&n=13",
         alt: "Минималистичный таунхаус с 3 спальнями",
      },
      countPhoto: 12,
      countVideo: 4,
   },
   {
      id: 5,
      title: "Шале в горах",
      address: "улица Горная, 8, поселок Горный воздух",
      price: "$6,000/mo",
      prevPrice: "$6,400/mo",
      beds: 6,
      baths: 5,
      garages: 2,
      area: 400,
      image: {
         url: "https://pershingtamilla.ru/wp-content/uploads/9/e/a/9ea30130cffefd085adae3fabaaaf297.jpeg",
         alt: "Роскошное шале с 6 спальнями и видом на горы",
      },
      countPhoto: 9,
      countVideo: 5,
   },
   {
      id: 6,
      title: "Белый островной дом",
      address: "улица Морская, 11, город Остров",
      price: "$4,000/mo",
      prevPrice: "$4,200/mo",
      beds: 4,
      baths: 3,
      garages: 1,
      area: 300,
      image: {
         url: "https://anvizbiometric.ru/wp-content/uploads/8/0/a/80a68db88d953f6c729157f9daf4c2ff.jpeg",
         alt: "Белый островной дом с 4 спальнями и бассейном",
      },
      countPhoto: 17,
      countVideo: 3,
   },
   {
      id: 7,
      title: "Кирпичный дворец",
      address: "проспект Королей, 2, город Замков и Усадеб",
      price: "$9,000/mo",
      prevPrice: "$9,500/mo",
      beds: 8,
      baths: 6,
      garages: 4,
      area: 600,
      image: {
         url: "https://rost-sk.com/wp-content/uploads/2023/03/dizayn-domov-2019-goda-sovremennye-arhitekturnye-proekty-interer_1.jpg",
         alt: "Огромный кирпичный дворец с 8 спальнями и огромным двором",
      },
   },
   {
      id: 8,
      title: "Скандинавский лофт",
      address: "улица Север, 56, город Светлые Ночи",
      price: "$2,900/mo",
      prevPrice: "$3,100/mo",
      beds: 4,
      baths: 3,
      garages: 1,
      area: 230,
      image: {
         url: "https://pershingtamilla.ru/wp-content/uploads/8/a/4/8a48f6da747cbe4ded27ab3a94471fca.jpeg",
         alt: "Скандинавский лофт с 4 спальнями и просторной террасой",
      },
      countPhoto: 14,
      countVideo: 1,
   },
];

// export const houseInfo = [
//    {
//       id: 1,
//       title: "Красивый дом на окраине города",
//       address: "ул. Лесная, 12",
//       price: 150000,
//       prevPrice: 170000,
//       beds: 3,
//       baths: 2,
//       garages: 1,
//       area: 120,
//       image: "https://example.com/image-1.jpg",
//       alt: "Фото дома на улице Лесной",
//    },
//    {
//       id: 2,
//       title: "Уютный дом в центре города",
//       address: "ул. Центральная, 5",
//       price: 200000,
//       prevPrice: 0,
//       beds: 4,
//       baths: 2,
//       garages: 2,
//       area: 150,
//       image: "https://example.com/image-2.jpg",
//       alt: "Фото дома на улице Центральной",
//    },
//    {
//       id: 3,
//       title: "Просторный дом с видом на озеро",
//       address: "ул. Озерная, 7",
//       price: 300000,
//       prevPrice: 350000,
//       beds: 5,
//       baths: 3,
//       garages: 3,
//       area: 200,
//       image: "https://example.com/image-3.jpg",
//       alt: "Фото дома на улице Озернлая",
//    },
//    {
//       id: 4,
//       title: "Коттедж в горах",
//       address: "ул. Горная, 2",
//       price: 400000,
//       prevPrice: 0,
//       beds: 6,
//       baths: 4,
//       garages: 4,
//       area: 250,
//       image: "https://example.com/image-4.jpg",
//       alt: "Фото коттеджа в горах",
//    },
//    {
//       id: 5,
//       title: "Дом у океана",
//       address: "ул. Океанская, 1",
//       price: 500000,
//       prevPrice: 600000,
//       beds: 7,
//       baths: 5,
//       garages: 5,
//       area: 300,
//       image: "https://example.com/image-5.jpg",
//       alt: "Фото дома у океана",
//    },
//    {
//       id: 6,
//       title: "Дом с бассейном и сауной",
//       address: "ул. Бассейновая, 10",
//       price: 250000,
//       prevPrice: 280000,
//       beds: 4,
//       baths: 3,
//       garages: 2,
//       area: 180,
//       image: "https://example.com/image-6.jpg",
//       alt: "Фото дома на улице Бассейновой",
//    },
//    {
//       id: 7,
//       title: "Модерн в стиле лофт",
//       address: "ул. Лофтная, 3",
//       price: 220000,
//       prevPrice: 0,
//       beds: 3,
//       baths: 2,
//       garages: 1,
//       area: 140,
//       image: "https://example.com/image-7.jpg",
//       alt: "Фото модерн дома",
//    },
//    {
//       id: 8,
//       title: "Квартира в новостройке",
//       address: "ул. Строительная, 5",
//       price: 120000,
//       prevPrice: 0,
//       beds: 2,
//       baths: 1,
//       garages: 0,
//       area: 80,
//       image: "https://example.com/image-8.jpg",
//       alt: "Фото квартиры в новостройке",
//    },
// ];
